pack_utils

[[    1     2 50256     3 50256 50256]]
[[    2 50256     3 50256 50256 50256]]
[[1 1 1 1 1 0]]


Packing shards: 100%|██████████| 100/100 [00:02<00:00, 37.14it/s]


In [ ]:
import numpy as np



SyntaxError: unterminated string literal (detected at line 47) (2095684810.py, line 47)

[[    1     2 50256     3 50256 50256]]
[[    2 50256     3 50256 50256 50256]]
[[1 1 1 1 1 0]]


In [227]:
print(tokenizer.decode(ids[3]))

 is


In [ ]:

# ❌ block packing
# ❌ labels
# ❌ loss masks
# ❌ train/val split
# ❌ report

# For a GPT-2 tokenizer there is no dedicated PAD token. In the function above I used tokenizer.eos_token_id as a
#  temporary placeholder because you haven't introduced a PAD token yet. Before finalizing this milestone, decide your
#  padding policy (or decide to drop the final partial block like nanoGPT). That decision determines whether your
#  loss mask is actually needed.

In [ ]:
from pathlib import Path




tokens = tokenizer.encode("ISMAIL")
tokens

[1797, 5673, 4146]

In [174]:
tokenizer.decode(tokens)

'ISMAIL'