pack_utils

[[    1     2 50256     3 50256 50256]]
[[    2 50256     3 50256 50256 50256]]
[[1 1 1 1 1 0]]


Packing shards: 100%|██████████| 100/100 [00:02<00:00, 37.14it/s]


In [ ]:
import numpy as np



SyntaxError: unterminated string literal (detected at line 47) (2095684810.py, line 47)

[[    1     2 50256     3 50256 50256]]
[[    2 50256     3 50256 50256 50256]]
[[1 1 1 1 1 0]]
